services:
  nav:
    image: nav:latest
    build: .
    container_name: nav
    network_mode: "host"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://nav:lh116688257@127.0.0.1:3306/nav
    volumes:
      - data:/app/data
    restart: unless-stopped

volumes:
  data:
