services:
  jg_nav:
    image: jg_nav:latest
    build: .
    container_name: jg_nav
    ports:
      - "13000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://nav:lh116688257@host.docker.internal:3306/nav
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - uploads:/app/public/uploads
    restart: unless-stopped

volumes:
  uploads:
