services:
  nav:
    image: nav:latest
    build: .
    container_name: nav
    ports:
      - "12266:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://nav:lh116688257@host.docker.internal:3306/nav
    volumes:
      - data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  data:
