services:
  nav:
    image: nav:latest
    build: .
    container_name: nav
    ports:
      - "13000:3000"
    environment:
      - NODE_ENV=production
      # 使用 1panel-network 网络中的 MySQL 容器
      - DATABASE_URL=mysql://root:lh116688257@mysql:3306/nav
    networks:
      - 1panel-network
    volumes:
      - data:/app/data
    restart: unless-stopped

networks:
  1panel-network:
    external: true

volumes:
  data:
